configuration-version: 1
experience:
  enabled: true
  chunk-window-seconds: 300
  chunk-soft-limit: 32
  chunk-hard-limit: 128
  farm-floor-multiplier: 0.10
  blocks:
    DIRT: 2
    GRASS_BLOCK: 2
    COARSE_DIRT: 2
    ROOTED_DIRT: 2
    PODZOL: 2
    MYCELIUM: 2
    MUD: 3
    PACKED_MUD: 3
    CLAY: 3
    SAND: 2
    RED_SAND: 2
    GRAVEL: 2
    SOUL_SAND: 2
    SOUL_SOIL: 2
    SNOW_BLOCK: 2
rewards:
  final-drop-multiplier-enabled: true
  rare-drops-enabled: true
